billilge/frontend

.github/labeler.yml, .github/workflows/autoLabel.yml, .github/workflows/autoReviewers.yml
- Closes #3 
어떤 변경 사항이 있나요?
- 일단 제 입맛대로 작성하긴 했는데 수정사항 있으시면 편하게 리뷰 남겨주세요~
=> [Init/#3] Github Action 세팅

tailwind.config.ts
- Closes #6
어떤 변경 사항이 있나요?
1. tailwind.config 에 피그마 기준 컬러 차트와 폰트를 세팅해두었습니다.
=> [Init/#6] tailwind.config 컬러, 폰트 세팅

src/app/mobile/page.tsx, src/components/mobile/layout/index.tsx
- Closes #15 
어떤 변경 사항이 있나요?
- mobile view setting을 위해 max-width가 768px인 layout을 만들었습니다.
- 더 작은 small moblie(500px)의 경우, 미디어 쿼리를 사용하면 될 거 같습니다!
- Layout의 props에 나중에 헤더의 title 변경에 따른 추가 요소가 있을 것 같아, 보기 쉽게 interface를 활용해 정의하였습니다.
- 코드 한 번씩 봐주세요☺️
아이폰 6 (375*667) 에서 보이는 화면입니다.
=> [init/#15]: 모바일 뷰를 위한 레이아웃 구현

src/app/mobile/page.tsx, src/app/mobile/sign-in/page.tsx, src/components/mobile/Spacing/index.tsx
- Closes #31 
어떤 변경 사항이 있나요?
- Spacing 공통 컴포넌트 생성
- 너무 넓은 Spacing이나 어디에 속하기 애매한 간격이 있을 때 사용하기 위한 Spacing 컴포넌트입니다
사용법은
```
<Spacing size={숫자} />
```
혹은 sm, lg같은 tailwind에 적용되는 글자를 string값으로 넘겨주면 돼요~!
toss의 Spacing 라이브러리를 참고했습니다.
[toss Spacing](https://www.slash.page/libraries/react/emotion-utils/src/spacing.i18n)
=> [Feat/#31] Spacing 공통 컴포넌트 추가

.eslintrc.json
- Closes #35 
```
interface TableComponentProps {
data: Invoice[];
showCheckboxes?: boolean; // 고민이에요... ESLint: propType "handleDelete" is not required, but has no corresponding defaultProps declaration 에러가 뜸
```
계속 ESLint 에러가 나서 defaultProps 를 사용하던 중, ESLint 설정을 변경하기로 했습니다.
=> [Fix/#35] ESLint 세팅 수정

src/app/globals.css, src/app/mobile/main/_components/MainHeader/index.tsx, src/app/mobile/main/page.tsx
- Closes #48 
어떤 변경 사항이 있나요?
1. 작업 내용
- 알림이 있을 경우에만 알림이 뜨도록
- 특정 브라우저에서 발생하는 웹 폰트 에러를 방지하기 위해 웹 폰트 추가
- test image 변경
-
우분투를 사용한 pc에서 크롬을 통해 접속했을 시 font error가 발생했었습니다.(이전에 캡쳐해둔 사진입니다!)
=> [Feat/#48] 알림이 있을 경우에만 알림이 뜨는 기능 / web font fix

public/manifest.json
- Closes #58 
어떤 변경 사항이 있나요?
- [-] 버그 수정
- [-] 🔀 PR 제목의 형식을 잘 작성했나요?
- [-] 🧹 불필요한 코드는 제거했나요? (TODO, 주석, clg... etc.)
- [-] ✅ 컨벤션을 지켰나요?
- [-] 💭 이슈는 등록했나요?
- [-] 🏷️ 라벨은 등록했나요?
- [-] 🙇‍♂️ 리뷰어를 지정했나요?
manifest.json 간단한 수정이었는데 브랜치 바꾸는 거 까먹고 작업해서 여기에 그냥 올려요..ㅎ
1. 작업 내용
프론트 파이팅하세요~
-
=> [Feat/#58] PWA 앱 배경색 및 이름 변경

public/manifest.json
- Closes #53 
어떤 변경 사항이 있나요?
1. 모바일 뷰에서 배경 색이 이상하게 설정되어 있던 현상을 수정하였습니다.
스크린샷에 수정 전 사진을 첨부하였습니다.
-
=> [Fix/#53] pwa 배경 색 수정

public/manifest.json, src/app/mobile/sign-in/page.tsx
- Closes #73
어떤 변경 사항이 있나요?
1. PWA 첫 진입 시 비로그인 상태에서 메인 화면이 잠시 보였다가 로그인 페이지로 리다이렉팅되는 현상을 수정했습니다. 
start_url을 메인화면으로 설정해두고 거기서 리다이렉팅시켜서 이런 현상이 일어났던 거 같습니다.
start_url을 sign-in으로 바꾸고 거기서 로컬스토리지에 토큰이 있는지 판별하고 메인페이지로 보내는 방식으로 수정했습니다.
2. 추가로 구글 로그인 버튼에 max width을 지정해서 데스크탑 화면에서 너무 길어보이지 않게 수정했습니다.
- 로그인 상태인지 아닌지 공통으로 뺀다고 하셨는데 공통으로 뺄 때 제가 sign-in에서 수정한 부분도 같이 수정해주시면 될 거 같아요~
=> [Fix/#73] PWA 첫 진입 시 비로그인 상태에서 메인 화면이 잠시 보이던 현상 수정

src/components/mobile/Header/index.tsx, src/components/mobile/NotificationItem/index.tsx
- Closes #82 
어떤 변경 사항이 있나요?
- 자잘한 디자인 이슈들 수정했습니다... notification에 알림 줄바꿈 가능하도록 수정 / 헤더 최상단 고정 및 폰트 사이즈, 아이콘 크기 변경
=> [Fix.#82] 자잘한 디자인 이슈 수정

.github/workflows/autoSync.yml
- Closes #86 
어떤 변경 사항이 있나요?
1. Vercel 배포 자동화를 위해 Github Actions workflow를 추가하였습니다.
- 네 그래요 화이팅
https://improvisation.tistory.com/entry/cicd
=> [Feat/#86] vercel 배포를 위한 repo 자동 동기화 구현

src/app/desktop/layout.tsx, src/app/layout.tsx, src/app/mobile/admin/dashboard/page.tsx, src/app/mobile/admin/notification/page.tsx, src/app/mobile/sign-in/page.tsx, src/components/mobile/layout/index.tsx, src/hooks/useAuthRedirect.ts, src/services/privateAxiosInstance.ts
- Closes #85 
어떤 변경 사항이 있나요?
로그인 / 어드민 여부 확인 후 로그인 혹은 메인으로 보내는 커스텀 훅 추가
- 코드가 많이 더러운데... 내일 일어나서 리팩토링 하든가 할게요 너무 졸려서 저능해지는 기분
=> [Feat/#85] 로그인/어드민 검사 기능 구현 

src/apis/rental.ts, src/components/mobile/Alert/index.tsx, src/components/mobile/BottomSheet/index.tsx, src/components/mobile/Header/index.tsx
- Closes #90 
어떤 변경 사항이 있나요?
1. 작업 내용
- 서버에서 중복 대여 응답 보낼 때 모달 띄우기
- 중복 대여 로직 추가
- 모달 max width 설정
- 모달 열고 닫는 애니메이션 추가
- 대여 시각 입력시, 현재 시각 이후로만 입력할 수 있도록 처리
< 추가 수정 >
- 헤더 z-index 추가
-
=> [Feat/#90] 서버에서 중복 대여 응답 보낼 때 모달 띄우기 / 모달 css 수정

src/app/mobile/history/page.tsx
- Closes #93 
어떤 변경 사항이 있나요?
1. 작업 내용
- 필터링 드롭다운메뉴 기능 추가 (선택한 텍스트로 바뀌도록)
- 대여기록 api 호출시점 변경 (alert창 먼저 닫고 api 호출)
-
제가 선택한 필터로 텍스트가 바뀜미다
=> [Feat/#93] 필터링 드롭다운메뉴 기능 추가 / 대여기록 api 호출시점 변경

src/app/layout.tsx
- Closes #77 
어떤 변경 사항이 있나요?
1. 작업 내용
모바일에서 input창 클릭시 확대되는 현상을 고쳤숩니다.
-
=> [fix/#77] input창 클릭시 확대 되는 현상 수정

src/app/mobile/main/page.tsx
- Closes #97 
어떤 변경 사항이 있나요?
1. 작업 내용
- 캐러셀의 링크를 노션 링크로 변경하였습니다.
- 아래의 링크로 변경하였습니다.
https://humdrum-puppet-86a.notion.site/1ab22817262580d9971cc464dc8e2c57?pvs=4
=> [Refactor/#97] carousel link 변경

src/app/mobile/sign-in/page.tsx, src/app/not-found.tsx
- Closes #101 
어떤 변경 사항이 있나요?
- not found 페이지 생성
- 현재 아무 url로 치고 들어가면  next 기본 404 페이지가 떠서 임시로 404 페이지로 이동하면 5초 뒤에 메인 페이지로 이동할 수 있도록 처리해 두었습니다~!
=> [Feat/#101] 404 페이지 생성

src/app/desktop/(nav-bar)/item-list/_components/ItemSidebar/index.tsx, src/app/desktop/(nav-bar)/item-list/_components/ItemTable/index.tsx, src/services/items.ts, src/types/items.ts
- Closes #96 
어떤 변경 사항이 있나요?
1. 물품 수정이 가능해졌습니다! 
2. 이미지 수정이 없을 경우 이미지는 넣지 않고 완료 누르면 됩니다.
3. 아직 기존 데이터를 불러오는 걸 못 해서... 일단 이미지 외 모든 정보를 수정해야 수정이 되는 상황입니다... 속히 해당 부분 수정하겠습니다. 그전에 수정이 필요할 수 있으니까 먼저 피알 올릴게요!
=> [Feat/#96] 물품 수정 api 연결

src/app/mobile/main/page.tsx
- Closes #124 
어떤 변경 사항이 있나요?
1. 작업 내용
팝업창 문구 변경 및 변수명 변경하였습니다.
-
=> [Feat/#124] 팝업창 문구 변경 및 변수명 변경

.github/workflows/autoSync-develop.yml, .github/workflows/autoSync-main.yml
- Closes #131 
어떤 변경 사항이 있나요?
1. 작업 내용
- 버셀로 배포하였고, 배포 버전 auto sync actions 추가
- 
https://datdaradanadat.tistory.com/177
=> [Chore/#131] dev용 배포
